"""freeze — laser_ro_nominal_v1  (bespoke, one substrate, brittle by design)

Materializes ONE settling curve for ONE class-B laser at ONE operating point.
The physics is OUR canonical class-B laser (mpa-central/library/ro_damping_audit.py,
laser_conform_Q.py; mpa-legal Finding 5). Ground truth comes from the Jacobian
eigenvalues directly — frame-invariant, never via conform (data-path independence).

Run:  python H:/mpa-conform/blockin/questions/laser_ro_nominal_v1/freeze_laser_ro.py

Emits:  data/laser_ro_nominal_v1.frozen.csv   (tau, C, chi  — the blind artifact)
        prints the SEALED ground truth (chit, gamma_RO, omega_RO, Q, zeta, regime)
        for the author to paste into entry.md. The CSV carries NONE of it.
"""
from __future__ import annotations
import sys
sys.stdout.reconfigure(encoding="utf-8")
from pathlib import Path
import numpy as np
from scipy.linalg import expm, solve_continuous_lyapunov

# --- our canonical class-B laser (G = kappa = 1, slow population gamma_s << kappa)
G, KAPPA, GAMMA_S = 1.0, 1.0, 0.10
# operating point: r = pump ratio = e^chit. r = 2 -> chit = ln2 = the Q-peak
# (mpa-legal: Q ∝ sqrt(r-1)/r peaks at r=2, independent of gamma_s). The healthiest
# damping — the interior of the underdamped band, overdamped walls on both sides.
R = 2.0
CHIT = float(np.log(R))

HERE = Path(__file__).resolve().parent
OUT = HERE / "data" / "laser_ro_nominal_v1.frozen.csv"


def jacobian(r):
    n_star = GAMMA_S * (r - 1.0)
    J = np.array([[0.0, G * n_star], [-KAPPA, -(GAMMA_S + G * n_star)]])
    return J, n_star


def native_RO(r):
    """Exact RO observables from the Jacobian eigenvalues (dimensionless Q is
    frame-invariant — no cadence/rescaling can move it)."""
    J, _ = jacobian(r)
    ev = np.linalg.eigvals(J)
    gamma_RO = float(-ev.real.mean())
    omega_RO = float(np.max(np.abs(ev.imag)))
    Q = omega_RO / (2.0 * gamma_RO) if (gamma_RO > 0 and omega_RO > 0) else 0.0
    zeta = gamma_RO / omega_RO if omega_RO > 0 else np.inf
    return gamma_RO, omega_RO, Q, zeta


def C_chi(r, t):
    """C(tau) = normalized photon-number autocorrelation; chi(tau) = integrated
    impulse response (the FDR susceptibility). Linear NESS propagator."""
    J, _ = jacobian(r)
    D = np.diag([max(GAMMA_S * (r - 1.0), 1e-6), GAMMA_S])
    Sigma = solve_continuous_lyapunov(J, -2.0 * D)
    C = np.empty_like(t); Rresp = np.empty_like(t)
    for i, ti in enumerate(t):
        P = expm(J * ti)
        C[i] = (P @ Sigma)[0, 0]
        Rresp[i] = P[0, 0]
    C = C / C[0]
    chi = np.concatenate([[0.0], np.cumsum(0.5 * (Rresp[1:] + Rresp[:-1]) * np.diff(t))])
    return C, chi


def main():
    g, w, Q, z = native_RO(R)
    # a few RO periods + envelope decay, physical time (substrate's own clock)
    period = 2.0 * np.pi / w
    t_max = max(6.0 * period, 8.0 / g)
    t = np.linspace(t_max / 400.0, t_max, 60)
    C, chi = C_chi(R, t)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# laser_ro_nominal_v1 — class-B laser settling curve, ONE operating point.\n")
        f.write(f"# substrate: class-B laser, G={G} kappa={KAPPA} gamma_s={GAMMA_S}, r={R} (one bias).\n")
        f.write("# columns: tau (substrate clock), C (normalized autocorr), chi (integrated response).\n")
        f.write("# C, chi dimensionless. Generated by the laser's own linear NESS propagator — not via conform.\n")
        f.write("tau,C,chi\n")
        for ti, ci, xi in zip(t, C, chi):
            f.write(f"{ti:.6f},{ci:.6f},{xi:.6f}\n")

    regime = "c (deep_c side of the Q-peak; underdamped RO band)" if Q > 0.5 else "overdamped"
    print("=== SEALED ground truth (author only — NOT in the CSV) ===")
    print(f"chit      = ln({R}) = {CHIT:.6f}")
    print(f"gamma_RO  = {g:.6f}   (= (gamma_s/2) e^chit, flows with chit)")
    print(f"omega_RO  = {w:.6f}")
    print(f"Q         = {Q:.6f}   (RO quality factor; peaks at r=2)")
    print(f"zeta      = {z:.6f}   (< 1 -> underdamped ring-down)")
    print(f"regime    = {regime}")
    print(f"\nwrote {OUT}  ({len(t)} rows)")


if __name__ == "__main__":
    main()
