r"""emergent_gain.py -- Move 2 (sharpened): does coarse-graining GENERATE collective self-gain (a>0)?

2A (mu z) and 2B (G_SELF R) failed at the SAME place: in both, autonomy was a WRITTEN-IN collective
self-amplification term. So the layer-2 crux collapses to one scalar (Ron, 2026-05-31): can coarse-graining
GENERATE a collective self-gain term -- effective positive feedback `a>0` in a collective coordinate -- rather
than merely SELECT among autonomy supplied externally?

THE TEST (Ron's 4 steps): (1) candidate collective coordinate X; (2) eliminate fast modes; (3) fit the reduced
  Xdot = a*X + b*X^3 + ...; (4) ask whether `a` crosses zero WITHOUT being inserted.

Candidate collective coordinate = the Kuramoto order parameter  R = |<e^{i theta}>|  (a coarse, collective,
amplitude-like variable; the units are pure PHASE, |z|=1, so NO per-unit amplitude gain is inserted -- any
a>0 in R is generated purely by the coupling/coarse-graining). All-to-all coupling is exactly mean-field:
  theta_i' = omega_i + K*R*sin(psi - theta_i - alpha),   psi = arg<e^{i theta}>.
We measure `a` as the early-time exponential rate of R off the incoherent state (R ~ R0 e^{a t} in the linear
regime), swept over coupling K, for two couplings:

  REPULSIVE / SPLAY base (alpha = 0.9*pi): the self-lit + gapped base from hybrid_generation/splay_cascade.
    PREDICTION (no-creation-of-gain corollary): a <= 0 for all K -- the splay's gain is TOPOLOGICAL (the Z2
    firing-order sector), with no amplitude gain to route into a collective amplitude coordinate. This is
    WHY 2A/2B had to insert.
  ATTRACTIVE ring (alpha = 0): the DETECTOR CALIBRATION + the honest positive. Synchronization onset is
    collective self-amplification GENERATED by coupling alone (Kuramoto, pa:kuramoto): a crosses zero at a
    real K_c, a>0 above it -- un-inserted emergent collective gain. Shows the test can FIRE.

VERDICT logic: splay a<=0 (no emergent gain, gain is topological) AND attractive a(K) crosses zero at finite
K_c (emergent gain is real, detector fires) => the SPLAY is the wrong base: self-lighting/gapped needs
REPULSION, collective gain needs ATTRACTION -- they pull opposite ways. That tension is the structural reason
2A/2B inserted, and it relocates the positive hunt to a base that reconciles the two (the deferred option b).

Usage (from mpa-conform root):  python scripts/emergent_gain.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

REPO_ROOT = Path(__file__).resolve().parents[1]
for p in (str(REPO_ROOT), str(REPO_ROOT / "scripts")):
    if p not in sys.path:
        sys.path.insert(0, p)

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

OUT = REPO_ROOT / "output" / "calibration"
OUT.mkdir(parents=True, exist_ok=True)

N = 200            # units (large -> incoherent floor ~1/sqrt(N) ~ 0.07, well below the R0 we impose)
OMEGA_STD = 0.5    # frequency spread -> finite K_c
DT = 0.01
T = 25.0
R0 = 0.20          # imposed initial coherence (above the floor; in the linear regime)
M_IC = 8           # ICs averaged per (K, alpha)
ALPHA_SPLAY = 0.9 * np.pi
ALPHA_ATTRACT = 0.0


def impose_coherence(rng, R_target):
    """phases from a wrapped-normal with R = exp(-sigma^2/2) = R_target."""
    sigma = float(np.sqrt(max(-2.0 * np.log(R_target), 1e-6)))
    return rng.normal(0.0, sigma, N)


def order_param(theta):
    z = np.mean(np.exp(1j * theta))
    return abs(z), np.angle(z)


def run_R(K, alpha, omega, seed):
    rng = np.random.default_rng(seed)
    theta = impose_coherence(rng, R0) + rng.uniform(0, 2 * np.pi)   # random mean phase
    nsteps = int(T / DT)
    Rt = np.empty(nsteps)
    for k in range(nsteps):
        R, psi = order_param(theta)
        Rt[k] = R
        theta = theta + (omega + K * R * np.sin(psi - theta - alpha)) * DT
    return Rt


def fit_gain(Rt):
    """a = early-time exponential rate of R in the linear window (R in [0.09, 0.32]); slope of ln R vs t."""
    t = np.arange(len(Rt)) * DT
    mask = (Rt > 0.09) & (Rt < 0.32)
    # restrict to the first contiguous run so we read the *initial* drift, not post-saturation wiggles
    if mask.sum() < 8:
        # R left the window almost immediately (fast decay) -> use the first 1.5 time-units
        mask = t < 1.5
    idx = np.where(mask)[0]
    idx = idx[idx <= idx[0] + int(4.0 / DT)]   # cap window length at 4 time-units
    lnR = np.log(np.clip(Rt[idx], 1e-6, None))
    a, _ = np.polyfit(t[idx], lnR, 1)
    return float(a)


def gain_curve(alpha, Ks, omega):
    a_mean, a_std = [], []
    for K in Ks:
        a_ics = [fit_gain(run_R(K, alpha, omega, seed=1000 * int(K * 10) + s)) for s in range(M_IC)]
        a_mean.append(float(np.mean(a_ics))); a_std.append(float(np.std(a_ics)))
    return np.array(a_mean), np.array(a_std)


def zero_crossing(Ks, a):
    """first K where a goes - -> + (linear interp). None if it never crosses up."""
    for i in range(len(Ks) - 1):
        if a[i] <= 0 < a[i + 1]:
            f = (0 - a[i]) / (a[i + 1] - a[i])
            return float(Ks[i] + f * (Ks[i + 1] - Ks[i]))
    return None


def main():
    rng = np.random.default_rng(7)
    omega = rng.normal(1.0, OMEGA_STD, N)
    Ks = np.linspace(0.0, 3.0, 13)

    print("Move 2 (sharpened) -- does coarse-graining GENERATE collective self-gain a>0 in R = |<e^{i th}>|?")
    print(f"N={N}, omega ~ Normal(1,{OMEGA_STD}), impose R0={R0}, fit a = early-time rate of ln R.  (units are")
    print(" pure phase, |z|=1 -> NO per-unit amplitude gain inserted; any a>0 in R is generated by coupling.)\n")

    a_sp, s_sp = gain_curve(ALPHA_SPLAY, Ks, omega)
    a_at, s_at = gain_curve(ALPHA_ATTRACT, Ks, omega)
    Kc_sp = zero_crossing(Ks, a_sp)
    Kc_at = zero_crossing(Ks, a_at)

    print("=" * 88)
    print("REPULSIVE / SPLAY base (alpha=0.9*pi) -- the self-lit + gapped base; predict a<=0 (gain topological)")
    print("=" * 88)
    for K, a, s in zip(Ks, a_sp, s_sp):
        print(f"  K={K:4.2f} | a = {a:+.4f} +/- {s:.4f}   {'<-- a>0' if a > 0.01 else ''}")
    print(f"  max a over K = {a_sp.max():+.4f}  | zero-crossing up: {Kc_sp}")

    print("\n" + "=" * 88)
    print("ATTRACTIVE ring (alpha=0) -- detector calibration + honest positive; predict a crosses 0 at K_c>0")
    print("=" * 88)
    for K, a, s in zip(Ks, a_at, s_at):
        print(f"  K={K:4.2f} | a = {a:+.4f} +/- {s:.4f}   {'<-- a>0' if a > 0.01 else ''}")
    print(f"  max a over K = {a_at.max():+.4f}  | zero-crossing up (K_c): "
          f"{Kc_at:.3f}" if Kc_at is not None else "  (never crosses up)")

    figure(Ks, a_sp, s_sp, a_at, s_at, Kc_at)

    splay_no_gain = bool(a_sp.max() <= 0.02)
    attract_emergent = bool(Kc_at is not None and a_at.max() > 0.05)
    print("\n" + "=" * 88)
    print("VERDICT -- can coarse-graining GENERATE collective self-gain (un-inserted)?")
    print("=" * 88)
    if attract_emergent and splay_no_gain:
        print("  ==> YES IN GENERAL, NO FOR THE SPLAY. Emergent collective self-gain is REAL: the attractive")
        print(f"      ring's collective coordinate R self-amplifies (a>0) above a generated threshold K_c~"
              f"{Kc_at:.2f} -- un-inserted, from COUPLING alone (units are pure phase, no per-unit gain). That")
        print("      is the synchronization transition: a>0 GENERATED by coarse-graining (Kuramoto). BUT the")
        print(f"      SPLAY base gives a<=0 for all K (max {a_sp.max():+.3f}): its gain is TOPOLOGICAL (the Z2")
        print("      firing-order sector), not amplitude gain -- nothing routes into the collective amplitude")
        print("      coordinate. ==> The splay is the WRONG base: self-lighting/gapped needs REPULSION,")
        print("      collective gain needs ATTRACTION -- they pull opposite ways. THIS is the structural")
        print("      reason 2A/2B had to insert. The positive hunt moves to a base reconciling the two")
        print("      (per-unit-gain / non-reciprocal / active-amplitude units -- the deferred option b).")
    else:
        print(f"  ==> Read honestly: splay max a={a_sp.max():+.4f} (no-gain={splay_no_gain}); "
              f"attractive max a={a_at.max():+.4f}, K_c={Kc_at} (emergent={attract_emergent}).")
    print("\n  SCOPE: minimal mean-field phase model; `a` is read empirically as the early-time rate of R off")
    print("  incoherence (the linear self-gain), not a full Ott-Antonsen reduction. The attractive case is")
    print("  textbook Kuramoto (pa:kuramoto) used here as the un-inserted positive control: it proves the")
    print("  detector fires and that emergent collective gain EXISTS -- isolating the splay's repulsion as")
    print("  the specific obstruction. Whether a base can be BOTH self-lit/gapped AND collective-gain-bearing")
    print("  is the remaining (option-b) question.")


def figure(Ks, a_sp, s_sp, a_at, s_at, Kc_at):
    fig, ax = plt.subplots(1, 2, figsize=(13, 5), dpi=150)
    ax[0].axhline(0, color="gray", lw=0.8)
    ax[0].errorbar(Ks, a_at, yerr=s_at, color="#2e7d32", lw=1.8, marker="o", ms=4,
                   label="attractive (alpha=0): emergent gain")
    ax[0].errorbar(Ks, a_sp, yerr=s_sp, color="#c62828", lw=1.8, marker="s", ms=4,
                   label="splay (alpha=0.9pi): no gain (topological)")
    if Kc_at is not None:
        ax[0].axvline(Kc_at, color="#2e7d32", ls="--", lw=1.2, label=f"K_c ~ {Kc_at:.2f} (gain generated)")
    ax[0].set_xlabel("coupling K"); ax[0].set_ylabel("collective self-gain  a  (rate of ln R)")
    ax[0].set_title("does `a` cross zero un-inserted?  attractive: YES at K_c;\nsplay: NO (a<=0 for all K)")
    ax[0].legend(fontsize=8, frameon=False); ax[0].grid(alpha=0.3)

    # illustrative R(t): attractive above K_c (grows) vs splay (decays)
    rng = np.random.default_rng(7)
    omega = rng.normal(1.0, OMEGA_STD, N)
    Rt_at = run_R(2.5, ALPHA_ATTRACT, omega, seed=1)
    Rt_sp = run_R(2.5, ALPHA_SPLAY, omega, seed=1)
    t = np.arange(len(Rt_at)) * DT
    ax[1].plot(t, Rt_at, color="#2e7d32", lw=1.6, label="attractive K=2.5: R self-amplifies (a>0)")
    ax[1].plot(t, Rt_sp, color="#c62828", lw=1.6, label="splay K=2.5: R decays (a<0)")
    ax[1].axhline(R0, color="gray", ls=":", lw=0.8, label=f"imposed R0={R0}")
    ax[1].set_xlabel("time"); ax[1].set_ylabel("collective coordinate R = |<e^{i th}>|")
    ax[1].set_title("the collective coordinate: GENERATED autonomy (attractive)\nvs restored-to-floor (splay)")
    ax[1].legend(fontsize=8, frameon=False); ax[1].grid(alpha=0.3)

    fig.suptitle("Move 2 (sharpened) -- emergent collective self-gain: generated by coupling (attractive) "
                 "but NOT by the splay (its gain is topological)", fontsize=11, weight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    path = OUT / "emergent_gain.png"
    fig.savefig(path, bbox_inches="tight"); plt.close(fig)
    print(f"\nfigure: {path}")


if __name__ == "__main__":
    main()
